// Auto-generated RTK Query endpoints from the OpenAPI schema.
// Do not edit this file manually — re-run the codegen script to update it.
import { baseApi as api } from './baseApi';
export const addTagTypes = [
  'Shops',
  'Categories',
  'Products',
  'Product Images',
  'Shop Logo',
  'Catalog',
  'Orders',
] as const;
const injectedRtkApi = api
  .enhanceEndpoints({
    addTagTypes,
  })
  .injectEndpoints({
    endpoints: (build) => ({
      getShops: build.query<GetShopsApiResponse, GetShopsApiArg>({
        query: () => ({ url: `/shops` }),
        providesTags: ['Shops'],
      }),
      createShop: build.mutation<CreateShopApiResponse, CreateShopApiArg>({
        query: (queryArg) => ({
          url: `/shops`,
          method: 'POST',
          body: queryArg,
        }),
        invalidatesTags: ['Shops'],
      }),
      getShopBySlug: build.query<GetShopBySlugApiResponse, GetShopBySlugApiArg>(
        {
          query: (queryArg) => ({ url: `/shops/slug/${queryArg}` }),
          providesTags: ['Shops'],
        },
      ),
      getMyShops: build.query<GetMyShopsApiResponse, GetMyShopsApiArg>({
        query: () => ({ url: `/shops/me` }),
        providesTags: ['Shops'],
      }),
      getShopById: build.query<GetShopByIdApiResponse, GetShopByIdApiArg>({
        query: (queryArg) => ({ url: `/shops/${queryArg}` }),
        providesTags: ['Shops'],
      }),
      updateShop: build.mutation<UpdateShopApiResponse, UpdateShopApiArg>({
        query: (queryArg) => ({
          url: `/shops/${queryArg.shopId}`,
          method: 'PATCH',
          body: queryArg.updateShopRequest,
        }),
        invalidatesTags: ['Shops'],
      }),
      deleteShop: build.mutation<DeleteShopApiResponse, DeleteShopApiArg>({
        query: (queryArg) => ({ url: `/shops/${queryArg}`, method: 'DELETE' }),
        invalidatesTags: ['Shops'],
      }),
      getCategoriesByShop: build.query<
        GetCategoriesByShopApiResponse,
        GetCategoriesByShopApiArg
      >({
        query: (queryArg) => ({ url: `/shops/${queryArg}/categories` }),
        providesTags: ['Categories'],
      }),
      createCategory: build.mutation<
        CreateCategoryApiResponse,
        CreateCategoryApiArg
      >({
        query: (queryArg) => ({
          url: `/shops/${queryArg.shopId}/categories`,
          method: 'POST',
          body: queryArg.createCategoryRequest,
        }),
        invalidatesTags: ['Categories'],
      }),
      getCategoryById: build.query<
        GetCategoryByIdApiResponse,
        GetCategoryByIdApiArg
      >({
        query: (queryArg) => ({
          url: `/shops/${queryArg.shopId}/categories/${queryArg.categoryId}`,
        }),
        providesTags: ['Categories'],
      }),
      updateCategory: build.mutation<
        UpdateCategoryApiResponse,
        UpdateCategoryApiArg
      >({
        query: (queryArg) => ({
          url: `/shops/${queryArg.shopId}/categories/${queryArg.categoryId}`,
          method: 'PATCH',
          body: queryArg.updateCategoryRequest,
        }),
        invalidatesTags: ['Categories'],
      }),
      deleteCategory: build.mutation<
        DeleteCategoryApiResponse,
        DeleteCategoryApiArg
      >({
        query: (queryArg) => ({
          url: `/shops/${queryArg.shopId}/categories/${queryArg.categoryId}`,
          method: 'DELETE',
        }),
        invalidatesTags: ['Categories'],
      }),
      getProductsByShop: build.query<
        GetProductsByShopApiResponse,
        GetProductsByShopApiArg
      >({
        query: (queryArg) => ({
          url: `/products`,
          params: {
            shopId: queryArg,
          },
        }),
        providesTags: ['Products'],
      }),
      createProduct: build.mutation<
        CreateProductApiResponse,
        CreateProductApiArg
      >({
        query: (queryArg) => ({
          url: `/products`,
          method: 'POST',
          body: queryArg,
        }),
        invalidatesTags: ['Products'],
      }),
      getProductById: build.query<
        GetProductByIdApiResponse,
        GetProductByIdApiArg
      >({
        query: (queryArg) => ({
          url: `/products/${queryArg.productId}`,
          params: {
            shopId: queryArg.shopId,
          },
        }),
        providesTags: ['Products'],
      }),
      updateProduct: build.mutation<
        UpdateProductApiResponse,
        UpdateProductApiArg
      >({
        query: (queryArg) => ({
          url: `/products/${queryArg.productId}`,
          method: 'PATCH',
          body: queryArg.updateProductRequest,
        }),
        invalidatesTags: ['Products'],
      }),
      deleteProduct: build.mutation<
        DeleteProductApiResponse,
        DeleteProductApiArg
      >({
        query: (queryArg) => ({
          url: `/products/${queryArg.productId}`,
          method: 'DELETE',
          params: {
            shopId: queryArg.shopId,
          },
        }),
        invalidatesTags: ['Products'],
      }),
      generateUploadUrl: build.mutation<
        GenerateUploadUrlApiResponse,
        GenerateUploadUrlApiArg
      >({
        query: (queryArg) => ({
          url: `/shops/${queryArg.shopId}/products/${queryArg.productId}/images/upload-url`,
          method: 'POST',
          body: queryArg.generateImageUploadUrlRequest,
        }),
        invalidatesTags: ['Product Images'],
      }),
      addProductImage: build.mutation<
        AddProductImageApiResponse,
        AddProductImageApiArg
      >({
        query: (queryArg) => ({
          url: `/shops/${queryArg.shopId}/products/${queryArg.productId}/images`,
          method: 'POST',
          body: queryArg.addProductImageRequest,
        }),
        invalidatesTags: ['Product Images'],
      }),
      generateShopLogoUploadUrl: build.mutation<
        GenerateShopLogoUploadUrlApiResponse,
        GenerateShopLogoUploadUrlApiArg
      >({
        query: (queryArg) => ({
          url: `/shops/${queryArg.shopId}/logo/upload-url`,
          method: 'POST',
          body: queryArg.generateShopLogoUploadUrlRequest,
        }),
        invalidatesTags: ['Shop Logo'],
      }),
      setShopLogo: build.mutation<SetShopLogoApiResponse, SetShopLogoApiArg>({
        query: (queryArg) => ({
          url: `/shops/${queryArg.shopId}/logo`,
          method: 'POST',
          body: queryArg.setShopLogoRequest,
        }),
        invalidatesTags: ['Shop Logo'],
      }),
      getCatalog: build.query<GetCatalogApiResponse, GetCatalogApiArg>({
        query: (queryArg) => ({
          url: `/shops/${queryArg.shopId}/catalog`,
          params: queryArg.lang ? { lang: queryArg.lang } : undefined,
        }),
        providesTags: ['Catalog'],
      }),
      createOrder: build.mutation<CreateOrderApiResponse, CreateOrderApiArg>({
        query: (queryArg) => ({
          url: `/orders`,
          method: 'POST',
          body: queryArg,
        }),
        invalidatesTags: ['Orders'],
      }),
      stripeWebhook: build.mutation<
        StripeWebhookApiResponse,
        StripeWebhookApiArg
      >({
        query: (queryArg) => ({
          url: `/webhooks/stripe`,
          method: 'POST',
          body: queryArg,
        }),
        invalidatesTags: ['Orders'],
      }),
      getOrdersByShop: build.query<
        GetOrdersByShopApiResponse,
        GetOrdersByShopApiArg
      >({
        query: (queryArg) => ({
          url: `/shops/${queryArg.shopId}/orders`,
          params: {
            page: queryArg.page,
            pageSize: queryArg.pageSize,
          },
        }),
        providesTags: ['Orders'],
      }),
      getOrderByPaymentIntent: build.query<
        GetOrderByPaymentIntentApiResponse,
        GetOrderByPaymentIntentApiArg
      >({
        query: (queryArg) => ({ url: `/orders/by-payment-intent/${queryArg}` }),
        providesTags: ['Orders'],
      }),
    }),
    overrideExisting: false,
  });
export { injectedRtkApi as api };
export type GetShopsApiResponse =
  /** status 200 List of all shops retrieved successfully */ GetAllShopsResponse;
export type GetShopsApiArg = void;
export type CreateShopApiResponse =
  /** status 200 Shop created successfully */ ShopResponse;
export type CreateShopApiArg = CreateShopRequest;
export type GetShopBySlugApiResponse =
  /** status 200 Shop retrieved successfully */ ShopResponse;
export type GetShopBySlugApiArg = /** Shop slug (public identifier) */ string;
export type GetMyShopsApiResponse =
  /** status 200 Shops where the user is an active owner member */ GetAllShopsResponse;
export type GetMyShopsApiArg = void;
export type GetShopByIdApiResponse =
  /** status 200 Shop retrieved successfully */ ShopResponse;
export type GetShopByIdApiArg = /** Shop ID */ string;
export type UpdateShopApiResponse =
  /** status 200 Shop updated successfully */ ShopResponse;
export type UpdateShopApiArg = {
  /** Shop ID */
  shopId: string;
  updateShopRequest: UpdateShopRequest;
};
export type DeleteShopApiResponse =
  /** status 200 Shop deleted successfully */ DeleteResponse;
export type DeleteShopApiArg = /** Shop ID */ string;
export type GetCategoriesByShopApiResponse =
  /** status 200 Categories retrieved successfully */ CategoriesResponse;
export type GetCategoriesByShopApiArg = /** Shop ID */ string;
export type CreateCategoryApiResponse =
  /** status 200 Category created successfully */ CategoryResponse;
export type CreateCategoryApiArg = {
  /** Shop ID */
  shopId: string;
  createCategoryRequest: CreateCategoryRequest;
};
export type GetCategoryByIdApiResponse =
  /** status 200 Category retrieved successfully */ CategoryResponse;
export type GetCategoryByIdApiArg = {
  /** Shop ID */
  shopId: string;
  /** Category ID */
  categoryId: string;
};
export type UpdateCategoryApiResponse =
  /** status 200 Category updated successfully */ CategoryResponse;
export type UpdateCategoryApiArg = {
  /** Shop ID */
  shopId: string;
  /** Category ID */
  categoryId: string;
  updateCategoryRequest: UpdateCategoryRequest;
};
export type DeleteCategoryApiResponse =
  /** status 200 Category deleted successfully */ CategoryResponse;
export type DeleteCategoryApiArg = {
  /** Shop ID */
  shopId: string;
  /** Category ID */
  categoryId: string;
};
export type GetProductsByShopApiResponse =
  /** status 200 Products retrieved successfully */ ProductsResponse;
export type GetProductsByShopApiArg = /** Shop ID to filter products */ string;
export type CreateProductApiResponse =
  /** status 200 Product created successfully */ ProductResponse;
export type CreateProductApiArg = CreateProductRequest;
export type GetProductByIdApiResponse =
  /** status 200 Product retrieved successfully */ ProductResponse;
export type GetProductByIdApiArg = {
  /** Product ID */
  productId: string;
  /** Shop ID (required for partition key) */
  shopId: string;
};
export type UpdateProductApiResponse =
  /** status 200 Product updated successfully */ ProductResponse;
export type UpdateProductApiArg = {
  /** Product ID */
  productId: string;
  updateProductRequest: UpdateProductRequest;
};
export type DeleteProductApiResponse =
  /** status 200 Product deleted successfully */ DeleteResponse;
export type DeleteProductApiArg = {
  /** Product ID */
  productId: string;
  /** Shop ID (required for partition key) */
  shopId: string;
};
export type GenerateUploadUrlApiResponse =
  /** status 200 Upload URL generated successfully */ GenerateImageUploadUrlResponse;
export type GenerateUploadUrlApiArg = {
  /** Shop ID */
  shopId: string;
  /** Product ID */
  productId: string;
  generateImageUploadUrlRequest: GenerateImageUploadUrlRequest;
};
export type AddProductImageApiResponse =
  /** status 200 Product image added successfully */ ProductImageResponse;
export type AddProductImageApiArg = {
  /** Shop ID */
  shopId: string;
  /** Product ID */
  productId: string;
  addProductImageRequest: AddProductImageRequest;
};
export type GenerateShopLogoUploadUrlApiResponse =
  /** status 200 Upload URL generated successfully */ GenerateShopLogoUploadUrlResponse;
export type GenerateShopLogoUploadUrlApiArg = {
  /** Shop ID */
  shopId: string;
  generateShopLogoUploadUrlRequest: GenerateShopLogoUploadUrlRequest;
};
export type SetShopLogoApiResponse =
  /** status 200 Shop logo updated successfully */ ShopResponse;
export type SetShopLogoApiArg = {
  /** Shop ID */
  shopId: string;
  setShopLogoRequest: SetShopLogoRequest;
};
export type GetCatalogApiResponse =
  /** status 200 Catalog retrieved successfully */ CatalogResponse;
export type GetCatalogApiArg = {
  /** Shop ID */
  shopId: string;
  /** Visitor's menu language (ISO 639-1); falls back to the shop's original language */
  lang?: string;
};
export type CreateOrderApiResponse =
  /** status 200 Order created and PaymentIntent initiated */ CheckoutResponse;
export type CreateOrderApiArg = CheckoutRequest;
export type StripeWebhookApiResponse = /** status 200 Event received */ {
  received?: boolean;
};
export type StripeWebhookApiArg = object;
export type GetOrdersByShopApiResponse =
  /** status 200 Orders retrieved successfully */ OrdersPageResponse;
export type GetOrdersByShopApiArg = {
  /** Shop ID */
  shopId: string;
  /** 1-based page number (default: 1) */
  page?: number;
  /** Number of orders per page (default: 20, max: 100) */
  pageSize?: number;
};
export type GetOrderByPaymentIntentApiResponse =
  /** status 200 Order found */ OrderByPaymentIntentResponse;
export type GetOrderByPaymentIntentApiArg =
  /** Stripe PaymentIntent ID (starts with pi_) */ string;
export type Address = {
  /** Street address */
  street?: string;
  /** City */
  city?: string;
  /** State or territory */
  state?: string;
  /** Postal code */
  postcode?: string;
  /** Country */
  country?: string;
};
export type ShopBranding = {
  /** Logo URL (must start with https://) */
  logoUrl?: string | null;
  /** Hero image URL (must start with https://) */
  heroImageUrl?: string | null;
  /** Accent color (hex) */
  accentColor?: string | null;
} | null;
export type OpeningTimeSlot = {
  /** Opening time (HH:mm, 24-hour) */
  open?: string;
  /** Closing time (HH:mm, 24-hour) */
  close?: string;
};
export type ShopResponse = {
  /** Shop ID */
  id?: string;
  /** Shop slug */
  slug?: string;
  /** Shop name */
  name?: string;
  /** Whether shop is deleted */
  isDeleted?: boolean;
  /** Whether shop is paused */
  isPaused?: boolean;
  /** Message shown when shop is paused */
  pausedMessage?: string;
  /** Shop currency (ISO code) */
  currency?: string;
  /** Shop timezone */
  timezone?: string;
  /** Minimum order amount in cents */
  minOrderAmountCents?: number;
  address?: Address;
  /** Creation timestamp */
  createdAt?: string;
  /** Last update timestamp */
  updatedAt?: string;
  /** Shop branding configuration, or null if not configured. */
  branding?: ShopBranding;
  /** Shop opening hours per day of the week. */
  openingHours?: {
    mon?: OpeningTimeSlot[];
    tue?: OpeningTimeSlot[];
    wed?: OpeningTimeSlot[];
    thu?: OpeningTimeSlot[];
    fri?: OpeningTimeSlot[];
    sat?: OpeningTimeSlot[];
    sun?: OpeningTimeSlot[];
  };
};
export type GetAllShopsResponse = {
  /** Array of shops */
  shops: ShopResponse[];
  /** Total number of shops */
  total: number;
};
export type ErrorResponse = {
  error?: string;
};
export type ShopClosure = {
  id?: string;
  start?: string;
  end?: string;
  reason?: string;
};
export type ShopMember = {
  userId?: string;
  role?: 'owner' | 'staff';
  isActive?: boolean;
};
export type CreateShopRequest = {
  /** Shop name (slug will be auto-generated from this) */
  name: string;
  /** Shop currency (ISO code) */
  currency: string;
  /** Shop timezone */
  timezone: string;
  /** Minimum order amount in cents */
  minOrderAmountCents: number;
  /** Payment policy */
  paymentPolicy: 'pay_online' | 'pay_in_person';
  address: Address;
  /** Message when shop is paused (optional) */
  pausedMessage?: string;
  /** Order acceptance mode (optional, defaults to auto) */
  orderAcceptanceMode?: 'auto';
  /** Shop opening hours for each day of the week. At least one day must have opening hours. */
  openingHours: {
    /** Monday opening hours */
    mon?: OpeningTimeSlot[];
    /** Tuesday opening hours */
    tue?: OpeningTimeSlot[];
    /** Wednesday opening hours */
    wed?: OpeningTimeSlot[];
    /** Thursday opening hours */
    thu?: OpeningTimeSlot[];
    /** Friday opening hours */
    fri?: OpeningTimeSlot[];
    /** Saturday opening hours */
    sat?: OpeningTimeSlot[];
    /** Sunday opening hours */
    sun?: OpeningTimeSlot[];
  };
  closures?: ShopClosure[];
  members?: ShopMember[];
  /** Shop branding configuration (optional). Set to null to disable branding. */
  branding?: ShopBranding;
};
export type UpdateShopRequest = {
  /** Shop name */
  name?: string;
  /** Whether shop is paused */
  isPaused?: boolean;
  /** Message when shop is paused */
  pausedMessage?: string;
  /** Payment policy */
  paymentPolicy?: 'pay_online' | 'pay_in_person';
  /** Shop currency */
  currency?: string;
  /** Shop timezone */
  timezone?: string;
  /** Minimum order amount in cents */
  minOrderAmountCents?: number;
  address?: Address;
  /** Shop branding configuration. Set to null to clear branding. */
  branding?: ShopBranding;
  /** Shop opening hours per day. At least one day must have opening hours. */
  openingHours?: {
    mon?: OpeningTimeSlot[];
    tue?: OpeningTimeSlot[];
    wed?: OpeningTimeSlot[];
    thu?: OpeningTimeSlot[];
    fri?: OpeningTimeSlot[];
    sat?: OpeningTimeSlot[];
    sun?: OpeningTimeSlot[];
  };
};
export type DeleteResponse = {
  /** Whether deletion was successful */
  success?: boolean;
};
export type CategoryResponse = {
  /** Category ID */
  id?: string;
  /** Shop ID */
  shopId?: string;
  /** Category name */
  name?: string;
  /** Sort order for display */
  sortOrder?: number;
  /** Lucide icon name */
  icon?: string;
  /** Whether category is deleted */
  isDeleted?: boolean;
  /** Creation timestamp */
  createdAt?: string;
  /** Last update timestamp */
  updatedAt?: string;
};
export type CategoriesResponse = CategoryResponse[];
export type CreateCategoryRequest = {
  /** Category name */
  name: string;
  /** Sort order for display */
  sortOrder?: number;
  /** Lucide icon name */
  icon?: string;
};
export type UpdateCategoryRequest = {
  /** Category name */
  name?: string;
  /** Sort order for display */
  sortOrder?: number;
  /** Lucide icon name */
  icon?: string;
};
export type ProductCategory = {
  /** Category ID */
  id?: string;
  /** Category name */
  name?: string;
  /** Category sort order */
  sortOrder?: number;
  /** Lucide icon name */
  icon?: string;
};
export type ProductImageRef = {
  /** Image ID */
  id?: string;
  /** Image URL */
  url?: string;
  /** Whether this is the primary image */
  isPrimary?: boolean;
};
export type VariantOption = {
  /** Option ID */
  id: string;
  /** Option name */
  name: string;
  /** Price delta in cents */
  priceDelta: number;
  /** Whether option is available */
  isAvailable: boolean;
};
export type VariantGroup = {
  /** Variant group ID */
  id: string;
  /** Variant group name */
  name: string;
  options: VariantOption[];
};
export type AddonOption = {
  /** Option ID */
  id: string;
  /** Option name */
  name: string;
  /** Price delta in cents */
  priceDelta: number;
  /** Whether option is available */
  isAvailable: boolean;
};
export type AddonGroup = {
  /** Addon group ID */
  id: string;
  /** Addon group name */
  name: string;
  /** Minimum selectable options */
  minSelectable: number;
  /** Maximum selectable options */
  maxSelectable: number;
  options: AddonOption[];
};
export type ProductSchedule = {
  /** Inclusive start date (YYYY-MM-DD) */
  startDate: string;
  /** Inclusive end date (YYYY-MM-DD); null = run indefinitely */
  endDate?: string | null;
  /** Daily window open (HH:mm, 24-hour); absent = 00:00 (all day) */
  startTime?: string | null;
  /** Daily window close (HH:mm, 24-hour); absent = 23:59 (all day) */
  endTime?: string | null;
  /** 0=Sun 1=Mon … 6=Sat; absent/empty = every day */
  daysOfWeek?: number[];
};
export type ProductResponse = {
  /** Product ID */
  id?: string;
  /** Shop ID */
  shopId?: string;
  /** Product name */
  name?: string;
  /** Product description */
  description?: string;
  /** Product price in cents */
  price?: number;
  /** Product categories with full details */
  categories?: ProductCategory[];
  /** Product images */
  images?: ProductImageRef[];
  /** Product variant groups (optional) */
  variantGroups?: VariantGroup[];
  /** Product addon groups (optional) */
  addonGroups?: AddonGroup[];
  /** Whether product is available */
  isAvailable?: boolean;
  /** Whether product is deleted */
  isDeleted?: boolean;
  /** Optional availability schedule; null = no time restriction */
  schedule?: ProductSchedule | null;
  /** Creation timestamp */
  createdAt?: string;
  /** Last update timestamp */
  updatedAt?: string;
};
export type ProductsResponse = ProductResponse[];
export type CreateProductRequest = {
  /** Shop ID that owns this product */
  shopId: string;
  /** Product name */
  name: string;
  /** Product description */
  description: string;
  /** Product price in cents */
  price: number;
  /** Category IDs */
  categoryIds?: string[];
  images?: ProductImageRef[];
  /** Whether product is available */
  isAvailable?: boolean;
  /** Optional availability schedule; null = no time restriction */
  schedule?: ProductSchedule | null;
};
export type UpdateProductRequest = {
  /** Shop ID (required for partition key) */
  shopId?: string;
  /** Product name */
  name?: string;
  /** Product description */
  description?: string;
  /** Product price in cents */
  price?: number;
  /** Category IDs */
  categoryIds?: string[];
  images?: ProductImageRef[];
  /** Whether product is available */
  isAvailable?: boolean;
  /** Variant groups (single-select per group, e.g. Size) */
  variantGroups?: VariantGroup[];
  /** Addon groups (multi-select per group, e.g. Extras) */
  addonGroups?: AddonGroup[];
  /** Optional availability schedule; null = no time restriction */
  schedule?: ProductSchedule | null;
};
export type GenerateImageUploadUrlResponse = {
  /** Unique identifier for the image */
  imageId: string;
  /** Pre-signed URL for uploading the image to Azure Blob Storage */
  uploadUrl: string;
  /** Permanent URL of the blob (without SAS token) */
  blobUrl: string;
  /** Expiration time of the upload URL */
  expiresAt: string;
};
export type GenerateImageUploadUrlRequest = {
  /** MIME type of the image to upload */
  contentType: 'image/jpeg' | 'image/png' | 'image/webp';
  /** Optional filename for the image */
  fileName?: string;
  /** Optional maximum file size in bytes */
  maxSizeBytes?: number;
};
export type ProductImageResponse = {
  /** Image ID */
  id: string;
  /** Image URL */
  url: string;
  /** Alternative text for the image */
  alt?: string;
  /** Sort order for displaying images */
  sortOrder: number;
  /** Whether this is the primary product image */
  isPrimary: boolean;
};
export type AddProductImageRequest = {
  /** Image ID returned from the upload URL generation */
  imageId: string;
  /** Blob URL of the uploaded image */
  url: string;
  /** Alternative text for the image */
  alt?: string;
  /** Sort order for displaying images */
  sortOrder?: number;
};
export type GenerateShopLogoUploadUrlResponse = {
  /** Unique identifier for the logo image */
  imageId: string;
  /** Pre-signed URL for uploading the logo to Azure Blob Storage */
  uploadUrl: string;
  /** Permanent URL of the logo blob (without SAS token) */
  blobUrl: string;
  /** Expiration time of the upload URL */
  expiresAt: string;
};
export type GenerateShopLogoUploadUrlRequest = {
  /** MIME type of the logo image to upload */
  contentType: 'image/jpeg' | 'image/png' | 'image/webp';
};
export type SetShopLogoRequest = {
  /** Image ID returned from the logo upload URL generation */
  imageId: string;
  /** Blob URL of the uploaded logo */
  url: string;
};
export type CatalogImageRef = {
  id?: string;
  url?: string;
  alt?: string | null;
  sortOrder?: number;
};
export type CatalogLabel = { id: string; label: string };
export type CatalogAdditive = { id: string; code: number; label: string };
export type CatalogProductDto = {
  /** Product ID */
  id?: string;
  /** Product name */
  name?: string;
  /** Product description */
  description?: string;
  /** Base price in cents */
  price?: number;
  images?: CatalogImageRef[];
  /** Variant groups */
  variants?: VariantGroup[];
  /** Addon groups */
  addons?: AddonGroup[];
  isAvailable?: boolean;
  /** Declared allergens, localized to the response language */
  allergens?: CatalogLabel[];
  /** Declared additives, localized to the response language */
  additives?: CatalogAdditive[];
  /** Dietary tags, localized to the response language */
  dietaryTags?: CatalogLabel[];
  /** Spiciness, localized to the response language, or null */
  spice?: CatalogLabel | null;
  /** Ways of ordering this dish is hidden for; hand-added, the generated client lags (TODO 5438) */
  unavailableModes?: ('collection' | 'delivery' | 'dine_in')[];
  createdAt?: string;
  updatedAt?: string;
};
export type CatalogCategoryDto = {
  /** Category ID */
  id?: string;
  /** Category name */
  name?: string;
  /** Display sort order */
  sortOrder?: number;
  /** Lucide icon name */
  icon?: string | null;
  products?: CatalogProductDto[];
};
export type CatalogResponse = {
  /** Language the categories and products are localized to */
  language?: 'de' | 'en';
  /** Menu languages the shop offers */
  languages?: Array<'de' | 'en'>;
  /** Categories with their visible, in-schedule products */
  categories: CatalogCategoryDto[];
};
export type CheckoutResponse = {
  /** Checkout session ID */
  sessionId: string;
  /** Stripe PaymentIntent client secret. Pass this to stripe.confirmPayment() on the frontend. */
  clientSecret: string;
  /** Server-computed order total in cents */
  subtotalCents: number;
  /** ISO currency code from the shop */
  currency: string;
};
export type CheckoutItem = {
  /** Product ID */
  productId: string;
  /** Quantity to order */
  quantity: number;
  /** ID of the selected variant option (e.g. size) */
  selectedVariantOptionId?: string;
  /** IDs of selected addon options */
  selectedAddonOptionIds?: string[];
};
export type CheckoutRequest = {
  /** ID of the shop to order from */
  shopId: string;
  /** Items to order */
  items: CheckoutItem[];
  /** Customer name */
  customerName: string;
  /** Customer email */
  customerEmail: string;
  /** Customer phone number */
  customerPhone: string;
  /** Optional notes for the order */
  customerNotes?: string;
  /** How the order will be fulfilled (defaults to collection when absent) */
  fulfilmentMode?: 'collection' | 'delivery' | 'dine_in';
};
export type OrderItemResponse = {
  productId: string;
  productName: string;
  quantity: number;
  unitPriceCents: number;
  selectedVariantOptionId?: string | null;
  selectedVariantOptionName?: string | null;
  selectedAddonOptionIds?: string[] | null;
  selectedAddonOptionNames?: string[] | null;
  lineTotalCents: number;
};
export type OrderResponse = {
  id: string;
  orderRef: string;
  status: 'pending_payment' | 'paid' | 'failed' | 'cancelled' | 'refunded';
  items: OrderItemResponse[];
  subtotalCents: number;
  currency: string;
  customerName: string;
  customerEmail: string;
  customerPhone: string;
  customerNotes?: string | null;
  createdAt: string;
};
export type OrdersPageResponse = {
  orders: OrderResponse[];
  total: number;
  page: number;
  pageSize: number;
};
export type OrderByPaymentIntentResponse = {
  orderId: string;
  orderRef: string;
  state:
    | 'PLACED'
    | 'ACCEPTED'
    | 'READY'
    | 'OUT_FOR_DELIVERY'
    | 'COMPLETED'
    | 'REJECTED'
    | 'CANCELLED';
  displayState:
    | 'PLACED'
    | 'ACCEPTED'
    | 'IN_PREPARATION'
    | 'READY'
    | 'OUT_FOR_DELIVERY'
    | 'COMPLETED'
    | 'REJECTED'
    | 'CANCELLED';
  fulfilmentMode: 'collection' | 'delivery' | 'dine_in';
  paymentStatus:
    | 'paid'
    | 'refunded'
    | 'partially_refunded'
    | 'cash_due'
    | 'cash_collected'
    | 'refunded_in_cash';
  readyAt: string | null;
  items: OrderItemResponse[];
  subtotalCents: number;
  currency: string;
  customerName: string;
  createdAt: string;
};
export const {
  useGetShopsQuery,
  useCreateShopMutation,
  useGetShopBySlugQuery,
  useGetMyShopsQuery,
  useGetShopByIdQuery,
  useUpdateShopMutation,
  useDeleteShopMutation,
  useGetCategoriesByShopQuery,
  useCreateCategoryMutation,
  useGetCategoryByIdQuery,
  useUpdateCategoryMutation,
  useDeleteCategoryMutation,
  useGetProductsByShopQuery,
  useCreateProductMutation,
  useGetProductByIdQuery,
  useUpdateProductMutation,
  useDeleteProductMutation,
  useGenerateUploadUrlMutation,
  useAddProductImageMutation,
  useGenerateShopLogoUploadUrlMutation,
  useSetShopLogoMutation,
  useGetCatalogQuery,
  useCreateOrderMutation,
  useStripeWebhookMutation,
  useGetOrdersByShopQuery,
  useGetOrderByPaymentIntentQuery,
} = injectedRtkApi;
